'use strict';
const el=id=>document.getElementById(id);
let scans=[],current=null,chosen=null,generation=0,saving=false;
async function api(url,options={}){const r=await fetch(url,options);const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail||d));return d;}
function message(t){el('message').textContent=t;}
function render(){el('items').replaceChildren();let all=0,closed=0,pending=0;for(const scan of scans)for(const page of scan.paginas.length?scan.paginas:[{pagina:0}]){all++;const s=page.revision?.estado||'SIN_REVISAR';closed+=s==='CONFIRMADO';pending+=s==='PENDIENTE';const f=el('status').value;if(f==='open'&&s==='CONFIRMADO'||f==='closed'&&s!=='CONFIRMADO'||f==='pending'&&s!=='PENDIENTE'||f==='error'&&scan.estado!=='ERROR')continue;if(!JSON.stringify([scan.nombre_original,page.coincidencias,page.sugerencias]).toLowerCase().includes(el('filter').value.toLowerCase()))continue;const b=document.createElement('button');b.className='item'+(current?.scan.id===scan.id&&current.page.pagina===page.pagina?' active':'');const title=document.createElement('strong');title.textContent=scan.nombre_original;b.append(title,document.createTextNode(`Página ${page.pagina||'—'} · ${scan.estado==='ERROR'?'ERROR':s}`));b.onclick=()=>open(scan,page);el('items').append(b);}el('summary').replaceChildren();for(const t of [`${scans.length} originales`,`${all} páginas/entradas`,`${closed} confirmadas`,`${pending} pendientes anotadas`]){const s=document.createElement('span');s.textContent=t;el('summary').append(s);}}
async function refresh(){const selected=current&&[current.scan.hash_sha256,current.page.pagina];const d=await api('/api/compras/ocr/bandeja');scans=d.scans;el('coverage').textContent=Object.entries(d.cobertura).map(([n,c])=>`${n}: ${c.archivos} exportes; fechas observadas ${c.primera_fecha||'—'} a ${c.ultima_fecha||'—'}.`).join(' ')+' No garantiza cobertura completa ni conexión en vivo. “No encontrado” no significa “falta cargar”.';if(selected){const scan=scans.find(s=>s.hash_sha256===selected[0]);if(scan)open(scan,scan.paginas.find(p=>p.pagina===selected[1])||{pagina:0});}render();}
function candidate(r,target){const b=document.createElement('button');b.className='candidate';b.textContent=`#${r.id} · ${r.proveedor} · ${r.control||r.motivo||r.status||''}${r.numero_comprobante?' · '+r.punto_venta+'-'+r.numero_comprobante:''}`;b.onclick=()=>{chosen=r.id;el('selected').textContent=`Seleccionada #${r.id}: ${r.proveedor}`;el('checked').checked=false;};target.append(b);}
function open(scan,page){generation++;current={scan,page};chosen=null;el('review-body').hidden=false;el('empty').hidden=true;el('selected').textContent='Sin factura seleccionada';el('search').value='';el('results').replaceChildren();el('checked').checked=false;el('append').checked=false;el('document-title').textContent=`${scan.nombre_original} · página ${page.pagina||'—'}`;const url=`/api/compras/ocr/${scan.id}/original`;el('original-link').href=url;el('original-link').hidden=false;const pdf=/\.pdf$/i.test(scan.nombre_original);el('pdf').hidden=!pdf;el('photo').hidden=pdf;if(pdf)el('pdf').src=url+`#page=${page.pagina||1}`;else el('photo').src=url;
 el('warnings').replaceChildren();for(const t of [scan.error,...(page.campos?.advertencias||[]),page.posible_duplicado?'Otra página propone la misma factura. Comprobar posible duplicado.':null].filter(Boolean)){const p=document.createElement('p');p.className='alert';p.textContent=t;el('warnings').append(p);}el('closed').textContent=page.revision?`${page.revision.estado} · ${page.revision.nota}`:'';el('closed').className=page.revision?.estado==='CONFIRMADO'?'success':'';el('candidates').replaceChildren();for(const r of page.coincidencias?.length?page.coincidencias:(page.sugerencias||[]))candidate(r,el('candidates'));
 const q=page.campos?.qr?.length===1?page.campos.qr[0]:null;let manual={};try{manual=JSON.parse(page.revision?.datos_json||'{}');}catch{}el('cuit').value=manual.cuit||q?.cuit||'';el('number').value=manual.numero||(q?`${q.punto_venta}-${q.numero}`:'');el('date').value=manual.fecha||q?.fecha||'';el('total').value=manual.total||(q?`${q.moneda} ${(q.total_centavos/100).toFixed(2)}`:'');el('pages').value=page.pagina||'';el('note').value=page.revision?.nota||'';el('text').textContent=JSON.stringify(page.campos||{},null,2)+'\n\n'+(page.texto||'')+'\n\nSEGUNDA LECTURA\n'+(page.texto_alternativo||'');el('history').textContent='Cargando…';const ticket=generation;api(`/api/compras/ocr/${scan.id}/historial`).then(h=>{if(ticket===generation)el('history').textContent=h.length?JSON.stringify(h,null,2):'Sin revisiones.';}).catch(e=>{if(ticket===generation)el('history').textContent=e.message;});render();}
async function search(){if(!current)return;const ticket=generation,q=el('search').value;chosen=null;el('selected').textContent='Sin factura seleccionada';el('checked').checked=false;el('results').replaceChildren();try{const d=await api('/api/compras/search?q='+encodeURIComponent(q));if(ticket!==generation||q!==el('search').value)return;for(const r of d.results)candidate(r,el('results'));if(!d.results.length)el('results').textContent='Sin resultados en los datos cargados.';}catch(e){message(e.message);}}
async function review(action){if(!current||saving)return;if(action==='CONFIRMADO'&&(!chosen||!el('checked').checked)){message('Seleccioná una factura y confirmá que comparaste el original.');return;}const raw=el('pages').value;if(!/^\s*\d+(\s*,\s*\d+)*\s*$/.test(raw)){message('Usá páginas separadas por coma.');return;}saving=true;el('confirm').disabled=el('pending').disabled=true;try{const r=await api(`/api/compras/ocr/${current.scan.id}/revisar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({paginas:raw.split(',').map(Number),accion:action,factura_id:chosen||0,nota:el('note').value,permitir_adjunto:el('append').checked,datos:{cuit:el('cuit').value,numero:el('number').value,fecha:el('date').value,total:el('total').value}})});message(r.message);await refresh();}catch(e){message(e.message);}finally{saving=false;el('confirm').disabled=el('pending').disabled=false;}}
el('upload').onclick=async()=>{const files=[...el('files').files];if(!files.length)return;el('upload').disabled=true;el('progress').max=files.length;el('progress').value=0;el('upload-log').replaceChildren();try{for(const file of files){const line=document.createElement('p');line.textContent=file.name+' · procesando…';el('upload-log').append(line);try{const form=new FormData();form.append('file',file);const r=await api('/api/compras/ocr/cargar',{method:'POST',body:form});line.textContent=file.name+' · '+r.estado+(r.error?' · '+r.error:'');}catch(e){line.textContent=file.name+' · ERROR: '+e.message;}el('progress').value++;}await refresh();}catch(e){message(e.message);}finally{el('upload').disabled=false;}};
el('retry').onclick=async()=>{if(!current)return;el('retry').disabled=true;try{const r=await api(`/api/compras/ocr/${current.scan.id}/reintentar`,{method:'POST'});message(r.error||'Lectura recuperada.');await refresh();}catch(e){message(e.message);}finally{el('retry').disabled=false;}};
el('confirm').onclick=()=>review('CONFIRMADO');el('pending').onclick=()=>review('PENDIENTE');el('find').onclick=search;el('search').oninput=()=>{chosen=null;el('checked').checked=false;el('selected').textContent='Sin factura seleccionada';};el('search').onkeydown=e=>{if(e.key==='Enter')search();};el('filter').oninput=render;el('status').onchange=render;el('refresh').onclick=()=>refresh().catch(e=>message(e.message));refresh().catch(e=>message(e.message));
